FROM registry.fedoraproject.org/fedora-minimal:42
ARG TARGETARCH
RUN if [ "${TARGETARCH}" = "amd64" ]; then microdnf install glibc -y; fi
COPY _out/hostpath-csi-driver /
ENTRYPOINT ["/hostpath-csi-driver"]

