apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: hostpath.csi.kubevirt.io
spec:
  # Supports persistent volumes.
  volumeLifecycleModes:
  - Persistent
  # To determine at runtime which mode a volume uses, pod info and its
  # "csi.storage.k8s.io/ephemeral" entry are needed.
  podInfoOnMount: true
